apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-rediclaim-sm
  namespace: monitoring
  labels:
    release: prometheus-stack  # Prometheus helm release 이름과 일치
spec:
  # 대상 Service 선택
  # Service 객체에 반드시 "app: mysql-rediclaim" 라벨이 있어야 함함
  selector:
    matchLabels:
      app: mysql-rediclaim
  # Scraping 대상 Service가 위치한 namespace 지정
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics  # 서비스의 metrics 포트 이름 (9104 포트 노출)
      path: /metrics # mysqld-exporter의 기본 메트릭 엔드포인트
      interval: 30s