apiVersion: apps/v1
kind: Deployment
metadata:
  name: judemin-coupon-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judemin-coupon-frontend
  template:
    metadata:
      labels:
        app: judemin-coupon-frontend
    spec:
      containers:
      - name: judemin-coupon-frontend
        image: judemin/coupon-frontend:latest
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: coupon-frontend-env
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: judemin-coupon-frontend
  labels:
    app: judemin-coupon-frontend
spec:
  type: NodePort
  selector:
    app: judemin-coupon-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---
#  k run -it --rm busybox --image=busybox --restart=Never -- sh \
#  -c "wget -qO- http://jayon0927-coupon-backend:8080/actuator/health"
apiVersion: v1
kind: ConfigMap
metadata:
  name: coupon-frontend-env
data:
  REACT_APP_API_BASE: ""