apiVersion: v1
kind: ConfigMap
metadata:
  name: coupon-backend-config
data:
  application.yaml: |-
    spring:
      datasource:
        name: rediclaim_db
        url: jdbc:mysql://mysql-rediclaim-service:3306/rediclaim_db?allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: _

      jpa:
        hibernate:
          ddl-auto: update
        database: mysql
        open-in-view: false

    data:
      redis:
        host: redis-min
        port: 6379

      kafka:
        # Kafka FQDN(Fully Qualified Domain Name)
        # CLIENT가 아니라 INTERNAL 주소를 사용
        bootstrap-servers: kafka-broker-headless.kafka.svc.cluster.local:9094
        producer:
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: coupon-backend-group
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "rediclaim.couponbackend.*"