apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jayon0927-coupon-backend-sm
  namespace: monitoring
  labels:
    # kube-prometheus-stack의 helm release 이름과 동일해야 함
    release: prometheus-stack
spec:
  # 어떤 Service를 모니터링할지 label 선택
  selector:
    matchLabels:
      app: jayon0927-coupon-backend

  # rediclaim-be의 Service가 존재하는 Namespace 지정
  namespaceSelector:
    matchNames:
      - default

  # 실제 Scraping 설정
  # SVC 포트 8080 -> 30002 으로 포트포워딩
  endpoints:
    - port: port8080
      # base-path: /actuator/prometheus에 맞추어 변경
      path: /actuator/prometheus
      interval: 30s