apiVersion: apps/v1
kind: Deployment
metadata:
  name: jayon0927-coupon-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jayon0927-coupon-backend
  template:
    metadata:
      labels:
        app: jayon0927-coupon-backend
    spec:
      containers:
      - name: jayon0927-coupon-backend
        image: jayon0927/coupon-backend
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "800m"
            memory: "800Mi"
          limits:
            cpu: "800m"
            memory: "800Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: coupon-backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: jayon0927-coupon-backend
  labels:
    app: jayon0927-coupon-backend
spec:
  type: NodePort
  selector:
    app: jayon0927-coupon-backend
  ports:
    - name: port8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
