apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-rediclaim-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mysql-rediclaim"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-rediclaim-pvc
spec:
  accessModes:
    - ReadWriteOnce           # 단일 노드에서만 Read/Write 가능한 모드
  storageClassName: manual    # 동적 프로비저닝 없이, 직접 PV를 만들겠다는 의미
  resources:
    requests:
      storage: 5Gi
  volumeName: mysql-rediclaim-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-exporter-rediclaim-config
data:
  .my.cnf: |
    [client]
    user=root
    password=_
    host=127.0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-rediclaim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rediclaim
  template:
    metadata:
      labels:
        app: mysql-rediclaim
    spec:
      containers:
        - name: mysql-rediclaim
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: _
            - name: MYSQL_ROOT_HOST # 루트 계정을 원격 접속 허용하려면 MYSQL_ROOT_HOST=%를 추가
              value: "%"
            - name: MYSQL_DATABASE
              value: rediclaim_db
            - name: MYSQL_USER
              value: rediclaim_user
            - name: MYSQL_PASSWORD
              value: _
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: mysql-rediclaim-data
              mountPath: /var/lib/mysql
        # mysqld_exporter sidecar
        - name: mysqld-exporter-rediclaim
          image: prom/mysqld-exporter:latest
          args:
            - "--config.my-cnf=/config/.my.cnf"
          ports:
            - containerPort: 9104
          resources:
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: mysql-exporter-rediclaim-config
              mountPath: /config/.my.cnf
              subPath: .my.cnf
      volumes:
        - name: mysql-rediclaim-data
          persistentVolumeClaim:
            claimName: mysql-rediclaim-pvc
        - name: mysql-exporter-rediclaim-config
          configMap:
            name: mysql-exporter-rediclaim-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-rediclaim-service
spec:
  type: NodePort
  selector:
    app: mysql-rediclaim
  ports:
    # MySQL
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32316
    # mysqld_exporter
    - name: metrics
      protocol: TCP
      port: 9104
      targetPort: 9104
      nodePort: 32114