apiVersion: apps/v1
kind: Deployment
metadata:
  name: thejasbabu-spring-actuator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thejasbabu-spring-actuator
  template:
    metadata:
      labels:
        app: thejasbabu-spring-actuator
    spec:
      containers:
      - name: thejasbabu-spring-actuator
        image: judemin/thejasbabu-spring-actuator:latest
        ports:
        - containerPort: 4001
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thejasbabu-spring-actuator
  # Scraping 연결을 위해 metadata.labels.app 추가
  labels:
    app: thejasbabu-spring-actuator 
spec:
  type: NodePort
  selector:
    app: thejasbabu-spring-actuator
  ports:
    - name: port4001
      protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30001
    - name: port8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
